# Use postgres/example user/password credentials
version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-nuxt}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: ${POSTGRES_DB:-nuxt-awesome}
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME:-nuxt-starter}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    ports:
      - "${POSTGRES_PORT}:5432"
